### ISSUE TITLE
corectld.runner: no such file or directory

### ISSUE THREAD

**Issue by mofm** [AntonioMeireles/coreos-xhyve#102]
It gives error** when I  command  "corectl run" . What is the reason? 

My Environment: macOS Sierra 10.12.1
 
$ corectl version

Server:
 Version:	0.7.18-7-g2b39d3+untagged
 Go Version:	go1.7.3
 Built:		Mon Jan 01 00:00:00 UTC 0001
 OS/Arch:	darwin/amd64

Client:
 Version:	0.7.18-7-g2b39d3+untagged
 Go Version:	go1.7.3
 Built:		Mon Jan 01 00:00:00 UTC 0001
 OS/Arch:	darwin/amd64
--
 suggested version is 0.7.18

** Error Log :

$ corectl run   
---> downloading and verifying alpha/1221.0.0
32.90 MB / 32.90 MB [=========================================================================] 100.00 % 
---> SHA512 hash for coreos_production_pxe.vmlinuz OK
232.96 MB / 232.96 MB [=======================================================================] 100.00 % 
---> SHA512 hash for coreos_production_pxe_image.cpio.gz OK
---> alpha/1221.0.0 ready
---> '7D50A99A-D8A9-4D0B-834D-1212CC0D34B3' boot logs can be found at '$HOME/.coreos/running/7D50A99A-D8A9-4D0B-834D-1212CC0D34B3/log'
[ERROR] fork/exec $HOME/prefix/usr/bin/corectld.runner: no such file or directory

**Comment by AntonioMeireles** [comment]
hmm... it looks like that you attempted to build corectl from tip by hand ... 
so you need to call it thru `./bin/corectl ...` as the remaining blobs location are found relative to `corectl` one. can you confirm that this was the issue please ?

**Comment by AntonioMeireles** [comment]
closing, due to lack of feedback. cannot reproduce too, and guess in previous comment seems about right.
