### ISSUE TITLE
DNS port should be configurable

### ISSUE THREAD

**Issue by vitaly** [AntonioMeireles/coreos-xhyve#106]
port `15353` that is hard-coded right now is also used by [mehserve](https://github.com/timecounts/mehserve)

> Note: I also opened an issue on mehserve: https://github.com/timecounts/mehserve/issues/10

**Comment by AntonioMeireles** [comment]
Hehe... that one is subtler... I can make it probably configurable at startup at will. Should have no big side effects. Need to look at code to be sure but certainly doable. Thanks for reporting!

**Comment by AntonioMeireles** [comment]
@vitaly 

Hi again, could you please fetch latest tip, built it, and confirm that it fixes this for you ? 
Thanks in advance!

**Comment by vitaly** [comment]
@AntonioMeireles sorry, as I mentioned I'm not a golang developer. I just tried to compile it and failed. spent a little time figuring it out, but I just don't feel like learning go and its ways. I have enough of language 'zoo' in my belt as it is ;) But if you make it into a proper release I'll definitely upgrade using the corectl.app and report back on results. Meanwhile I just submited a PM for mehserve (I do know js ;)) so I have the NDS port conflict sorted out, now only problem is the firewall rules mess.

**Comment by vitaly** [comment]
OK, so I finally got it to compile using hints from `/Applications/corectl.app/Contents/Resources/get_go_binaries/corectl_compile_from_source_corectl.sh`

DNS port configuration seems to be working, but PF rules are still messed up. Actually it seems to be worse, as I can't even connect outside from a VM. I'll provide more details on https://github.com/TheNewNormal/corectl/issues/105

**Comment by AntonioMeireles** [comment]
this one should have no *undesired* features. closing as things seem to do what we expect them to.
