### ISSUE TITLE
/etc/exports

### ISSUE THREAD

**Issue by rimusz** [AntonioMeireles/coreos-xhyve#19]
there are duplicate records:

```
/Users -network 192.168.64.0 -mask 255.255.255.0 -alldirs -mapall=505:20

/Users -network 192.168.64.0 -mask 255.255.255.0 -alldirs -mapall=503:20
```

`correctl` should check for existing record before updating `/etc/exports`

**Comment by AntonioMeireles** [comment]
it is. **the records are not a duplicate**, as (UID) **503 != 505**. what this means is that you 've called `corectl` under two different users in same system...

i know this is suboptimal but to get around this we'd have to think about placing all that is right now under `~/.coreos` into some global dir, etc, and, so far, the point about `corectl`'s use case was about it being single user...

**Comment by rimusz** [comment]
right  I see, as I used `correctl` with two different users on the sam Mac.
sorry for the noise
