### ISSUE TITLE
v0.0.6 problems 

### ISSUE THREAD

**Issue by rimusz** [AntonioMeireles/coreos-xhyve#2]
VM gets started but is not listed and not accessible via ssh:

```
[corectl] beta/835.1.0 already available on your system
[corectl] started 'coreos-01' in background with IP 192.168.64.2 and PID 964
[corectl] found 0 running VMs, summing 0 vCPUs and 0MB in use.

corectl ssh coreos-01
Error: 'coreos-01' not found, or dead

Usage:
  corectl ssh [flags]
...
```

**Comment by AntonioMeireles** [comment]
_this_ is interesting. is this reproduceable ? is VM listed in `corectl ps` ? pid 964 exists ? is this with -d (detached mode) ?

**Comment by AntonioMeireles** [comment]
oops. reproduceable. wiil try to fix it over weekend.

**Comment by AntonioMeireles** [comment]
@rimusz about to release 0.6.1 to consume this in a bit

**Comment by rimusz** [comment]
v0.0.7 does work fine, thanks
