### ISSUE TITLE
support fully functional static IPs

### ISSUE THREAD

**Issue by rimusz** [AntonioMeireles/coreos-xhyve#41]
An option to set a static IP for VM/s

**Comment by AntonioMeireles** [comment]
my findings, so far, on this...

on _paper_ all of what one would to do would be to populate `/etc/bootptab`, along ...

```
#
%%
#
# 4C1B3754-65AB-446C-8327-EED96F3FA1FA => 5a:b6:3a:33:cf:32
# hostname      hwtype  hwaddr              ipaddr          bootfile
foo 1 5a:b6:3a:33:cf:32 192.168.64.199 boot
```

and then (on a plain xhyve checkout), with the patch bellow applied ...

```
diff --git a/xhyverun.sh b/xhyverun.sh
index fcd7185..e05504b 100755
--- a/xhyverun.sh
+++ b/xhyverun.sh
@@ -12,14 +12,14 @@ CMDLINE="earlyprintk=serial console=ttyS0"

 MEM="-m 1G"
 #SMP="-c 2"
-#NET="-s 2:0,virtio-net"
+NET="-s 2:0,virtio-net"
 #IMG_CD="-s 3,ahci-cd,/somepath/somefile.iso"
 #IMG_HDD="-s 4,virtio-blk,/somepath/somefile.img"
 PCI_DEV="-s 0:0,hostbridge -s 31,lpc"
 LPC_DEV="-l com1,stdio"
 ACPI="-A"
 #UUID="-U deadbeef-dead-dead-dead-deaddeafbeef"
-
+UUID="-U 4C1B3754-65AB-446C-8327-EED96F3FA1FA"
 # Linux
 build/xhyve $ACPI $MEM $SMP $PCI_DEV $LPC_DEV $NET $IMG_CD $IMG_HDD $UUID -f kexec,$KERNEL,$INITRD,"$CMDLINE"
```

calling  `sudo ./xhyverun.sh` would have got us a VM with IP `192.168.64.199`.

point is - **it does**, BUT it’s just that that VM looks unable to reach/be reached to/from anything. can’t reach `192.168.64.1`, even, and from the host `arp -i bridge100 -a` gives nothing. (i’m on a fully up to date 10.10). FWIW on xhyve source (`src/pci_virtio_net_vmnet.c`) there’s a note pointing to http://github.com/mirage/ocaml-vmnet which served as inspiration for xhyve’s vmnet support. it’s there (https://github.com/mirage/ocaml-vmnet/issues/3) that - so far - i’ve found the only report of a similar (mis)behaviour to the one i’m hitting. So, open questions are - doesn’t vmnet framework supports static IPs?, or has a different way to achieve them ?, or it’s xhyve’s (and previously ocaml’s) consumption of vmnet that is missing on that front?  (or it's just me missing the obvious)

**Comment by AntonioMeireles** [comment]
we now support full name based resolution on the guests and between guests so, from a practical point of view, from our expected use cases, this become a moot point. _IF_ there's still a pertinent use case for this specific feature we'll reopen. 

FWIW the issue i've open at [Apple's bugacker](https://bugreport.apple.com) a bug (case id 24204697) with the original underlying (macOS) issue it's still on their queue (and was marked as valid)
