### ISSUE TITLE
sometimes VM crashes for no reason

### ISSUE THREAD

**Issue by rimusz** [AntonioMeireles/coreos-xhyve#57]
I was running `kube-cluster` and one of VM's just crashed after using the cluster for 40 min

**Comment by AntonioMeireles** [comment]
@rimusz would need way more data, and ideally a deterministic way to induce this... in the meantime - anything on host's logs ? running any specific payload inside the deceased VM ?

**Comment by rimusz** [comment]
I was using alpha there, lets see if it happens again on stable/beta

**Comment by rimusz** [comment]
I was not able to reproduce this one anymore, closing it
