### ISSUE TITLE
ISO download problem

### ISSUE THREAD

**Issue by rimusz** [AntonioMeireles/coreos-xhyve#59]
if empty e.g. `/.coreos/images/stable/835.12.0` folder exits, fetching latest iso version does not work:

```
[corectl] stable/835.12.0 already available on your system
```

**Comment by AntonioMeireles** [comment]
yup, lazy check :cry: . will be fixed. by the way - actual `.coreos/images/stable/835.12.0/` contents vanished how ?

**Comment by rimusz** [comment]
yep, it did vanish for some reason

**Comment by AntonioMeireles** [comment]
https://github.com/TheNewNormal/corectl/commit/862c94e2217574f75aef24894db976dfae8bd73c _should_ alleviate this for the common case... (more strict checks will come soon)

**Comment by AntonioMeireles** [comment]
i thinks this is solved, if not please reopen.
