### ISSUE TITLE
Interrupted/corrupt image download causes freak-out

### ISSUE THREAD

**Issue by quinncomendant** [AntonioMeireles/coreos-xhyve#60]
I'm on a medieval internet connection which struggles to download anything larger than 100M. So far I have not successfully completed the download phase of `corectl run`. I'd like to report that corectl doesn't behave well when this situation occurs:
1. Installed corectl, xhyve, docker, and friends via homebrew.
2. Running `sudo corectl run` begins the download process.
3. `coreos_production_pxe.vmlinuz` download completes successfully (_hash OK_).
4. `coreos_production_pxe_image.cpio.gz` download is interrupted (_hash verification failed_).
5. The corectl help screen prints.
6. `sudo corectl ps` shows _found 0 running VMs_.
7. `sudo corectl ls` shows one available image.
8. `sudo corectl run` shows _kexec: failed to load kernel_ and then my terminal session becomes corrupted so that line feeds are not respected. Doing `Shell` > `Reset` or `Hard Reset` doesn't help (need to close terminal window and start over). When I hit `return` multiple times my prompt stacks like this:
   
   [q@skillet/0 ~] [q@skillet/0 ~] [q@skillet/0 ~] [q@skillet/0 ~] 

There are two problems to report here: 
1. Failed download is not caught gracefully (this might be solved in #59). corectl should clean the environment so `corectl run` can start afresh.
2. Terminal freakout with stacked prompts—why is that happening?

Here's the full terminal transcript from my session:

```
[q@skillet/0 ~] sudo corectl run
[corectl] downloading and verifying alpha/960.0.0
30.11 MB / 30.11 MB [=====================================================================================================] 100.00 % 
[corectl] SHA512 hash for coreos_production_pxe.vmlinuz OK
185.44 MB / 199.16 MB [=========================================================================================>------] 93.11 % 6m5s
Error: SHA512 hash verification failed for coreos_production_pxe_image.cpio.gz

Usage: 
  corectl run [flags]

Aliases:
  run, start

Flags:
      --cdrom string          append an CDROM (.iso) to VM
      --channel string        CoreOS channel (default "alpha")
      --cloud_config string   cloud-config file location (either a remote URL or a local path)
      --cpus int              VM's vCPUS (default 1)
  -d, --detached              starts the VM in detached (background) mode
  -h, --help                  help for run
  -l, --local latest          consumes whatever image is latest locally instead of looking online unless there's nothing available.
      --memory int            VM's RAM, in MB, per instance (1024 < memory < 8192) (default 1024)
  -n, --name string           names the VM. (if absent defaults to VM's UUID)
      --root string           append a (persistent) root volume to VM
      --sshkey string         VM's default ssh key
      --tap string            append tap interface to VM
      --uuid string           VM's UUID (default "random")
      --version string        CoreOS version (default "latest")
      --volume value          append disk volumes to VM (default [])

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"
[q@skillet/0 ~] sudo corectl ps
[corectl] found 0 running VMs, summing 0 vCPUs and 0MB in use.
[q@skillet/0 ~] sudo corectl ls
locally available images
  - alpha channel 
    - 960.0.0
[q@skillet/0 ~] sudo corectl run
[corectl] alpha/960.0.0 already available on your system
[corectl] '/Users/q' was already available to VMs via NFS
kexec: failed to load kernel /Users/q/.coreos/images/alpha/960.0.0/coreos_production_pxe.vmlinuz
[q@skillet/0 ~] [q@skillet/0 ~] [q@skillet/0 ~] [q@skillet/0 ~] 
```

**Comment by AntonioMeireles** [comment]
@quinncomendant hi, thnks for reporting!. i believe that current tip fixes this (or at least mitigates it). i'll cut a new formal release in next 24 hrs. (i've been a _bit_ too busy in the last few days :-( )

**Comment by quinncomendant** [comment]
Hi @AntonioMeireles, thanks for the fast reply. What do you mean by “that current tip”? I look forward to future releases. I'm loving coreos and looking forward to using it as a development environment.

In the meantime, I'm making a fourth attempt to download the ISO—crossing fingers that it completes. ;P

It might be good to download files to a `~/.coreos/tmp/` directory and once the download completes and hash is verified, move it to `~/.coreos/images/`.

BTW, I noticed several sub-directories and config files have been created under the `~/.coreos/running/` directory. Shouldn't these be removed when I do `corectl rm` (which I've been running to clean the downloads before retrying)?  Should I just remove them manually?

```
[q@skillet/0 ~] find .coreos
.coreos
.coreos/images
.coreos/images/alpha
.coreos/images/alpha/960.0.0
.coreos/images/beta
.coreos/images/stable
.coreos/running
.coreos/running/4ecc2335-2fb8-4b17-8b47-17b08ebc7e24
.coreos/running/4ecc2335-2fb8-4b17-8b47-17b08ebc7e24/config
.coreos/running/80b08d09-89dc-4dde-a84a-1d3612c374a8
.coreos/running/80b08d09-89dc-4dde-a84a-1d3612c374a8/config
.coreos/running/c209bd66-288b-4168-a3a0-34d714c08bfe
.coreos/running/c209bd66-288b-4168-a3a0-34d714c08bfe/config
```

**Comment by AntonioMeireles** [comment]
i hope https://github.com/TheNewNormal/corectl/commit/862c94e2217574f75aef24894db976dfae8bd73c fixes this issue for the common case. so building from tip tree (plain git checkout _should_ work hopefully to fix this)

**Comment by quinncomendant** [comment]
And an ETA for the brew version to include this update? Are you responsible for the pushing the brew recipe?

**Comment by AntonioMeireles** [comment]
tommorrow. `brew install --HEAD corectl` should work _now_ btw (building from tip)

**Comment by quinncomendant** [comment]
PS: Regarding the corrupt terminal after corectl aborts, I'm able to restore the terminal by running `tput reset`. Because that fixes it, I'm guessing when corectl aborts it outputs binary data to the screen.

**Comment by quinncomendant** [comment]
BTW, `brew install --HEAD corectl` doesn't build for me…

```
[q@skillet/0 ~] brew install --HEAD corectl
==> Cloning https://github.com/TheNewNormal/corectl.git
Updating /Library/Caches/Homebrew/corectl--git
==> Checking out branch golang
==> make corectl
Last 15 lines from /Users/q/Library/Logs/Homebrew/corectl/01.make:
    /private/tmp/corectl20160218-8436-ypttx7/src/golang.org/x/crypto/openpgp
helpers.go:48:2: cannot find package "golang.org/x/crypto/openpgp/clearsign" in any of:
    /usr/local/Cellar/go/1.5.3/libexec/src/golang.org/x/crypto/openpgp/clearsign (from $GOROOT)
    /private/tmp/corectl20160218-8436-ypttx7/Godeps/_workspace/src/golang.org/x/crypto/openpgp/clearsign (from $GOPATH)
    /private/tmp/corectl20160218-8436-ypttx7/src/golang.org/x/crypto/openpgp/clearsign
helpers.go:49:2: cannot find package "golang.org/x/crypto/ssh" in any of:
    /usr/local/Cellar/go/1.5.3/libexec/src/golang.org/x/crypto/ssh (from $GOROOT)
    /private/tmp/corectl20160218-8436-ypttx7/Godeps/_workspace/src/golang.org/x/crypto/ssh (from $GOPATH)
    /private/tmp/corectl20160218-8436-ypttx7/src/golang.org/x/crypto/ssh
ssh.go:31:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
    /usr/local/Cellar/go/1.5.3/libexec/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
    /private/tmp/corectl20160218-8436-ypttx7/Godeps/_workspace/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
    /private/tmp/corectl20160218-8436-ypttx7/src/golang.org/x/crypto/ssh/terminal
godep: go exit status 1
make: *** [corectl] Error 1

READ THIS: https://git.io/brew-troubleshooting
```

**Comment by AntonioMeireles** [comment]
i believe that this is now fixed.
