### ISSUE TITLE
“simple usage recipe: a docker and rkt playground” doesn't fulfill promises

### ISSUE THREAD

**Issue by quinncomendant** [AntonioMeireles/coreos-xhyve#64]
I've followed the instructions under _simple usage recipe: a docker and rkt playground_ but have noticed that my result is different than what is promised. 
1. The instructions claim the cloud-config will _bind mount both /var/lib/rkt and /var/lib/docker_ but that is not happening. After booting, only /var/lib/rkt exists:
   
   ```
   core@containerLand ~ $ df
   Filesystem            1K-blocks      Used Available Use% Mounted on
   devtmpfs                 393724         0    393724   0% /dev
   tmpfs                    510652         0    510652   0% /dev/shm
   tmpfs                    510652     12980    497672   3% /run
   tmpfs                    510652         0    510652   0% /sys/fs/cgroup
   tmpfs                    510652      6944    503708   2% /
   /dev/loop0               205184    205184         0 100% /usr
   tmpfs                    510652         0    510652   0% /tmp
   tmpfs                    510652         0    510652   0% /media
   192.168.64.1:/Users/q 487368864 409198720  77914144  85% /Users/q
   /dev/vda                5029504     10388   5002732   1% /var/lib/rkt
   ```
2. Also, _docker will also become available through socket activation_ does not seem to be true. There is no docker.sock file created on the OS X host:
   
   ```
   [q@osx ~] ll /var/run/docker.sock
   ls: /var/run/docker.sock: No such file or directory
   [q@osx ~] find / -name docker.sock
   (nothing found)
   [q@osx ~] docker images
   Cannot connect to the Docker daemon. Is the docker daemon running on this host?
   ```
   
   The docker.sock _does exist_ within the VM however. I'm just assuming `corectl` would function similar to the [DLite](https://github.com/nlf/dlite) project and create the socket on the host so docker has access to the daemon running inside coreos. Otherwise, what is notable about the creation of docker.sock on the VM?
3. The output from `corectl ps` included in the instructions is different than what I get after booting `containerland` (the given example output displays one additional VM):
   
   ```
   [q@osx ~] corectl ps
   [corectl] found 1 running VMs, summing 1 vCPUs and 1024MB in use.
   - containerland, alpha/962.0.0, PID 23610 (detached=true), up 2m3.825610324s
     - 1 vCPU(s), 1024 RAM
     - cloud-config: /usr/local/Cellar/corectl/0.5.4/share/cloud-init/docker-only-with-persistent-storage.txt
     - Network Interfaces:
       - eth0 (public interface) 192.168.64.17
     - Volumes:
       - /dev/vda (/Users/q/var/var_lib_docker.img)
   ```

**Comment by quinncomendant** [comment]
Perhaps I'm wrong about `/var/lib/docker` not being mounted. Although it isn't listed in the output from `df`, the volume does exist and does persist between reboots (see here I ran `sudo touch /var/lib/{rkt,docker}` and restarted coreos before listing this output:

```
core@containerLand ~ $ sudo ls -alF /var/lib/{rkt,docker}/test
-rw-r--r-- 1 root root 0 Feb 23 22:01 /var/lib/docker/test
-rw-r--r-- 1 root root 0 Feb 23 22:01 /var/lib/rkt/test
```

**Comment by AntonioMeireles** [comment]
closing as not an issue in our side (as comment above shows)
