### ISSUE TITLE
fleetctl list-machines: Error retrieving list of active machines

### ISSUE THREAD

**Issue by olalonde** [AntonioMeireles/coreos-xhyve#70]
If I understand correctly, VMs launched with `corectl run` don't have etcd and fleet pre-configured right?

``` bash
core@core3 ~ $ fleetctl list-machines
Error retrieving list of active machines: Get http://domain-sock/fleet/v1/machines?alt=json: dial unix /var/run/fleet.sock: connect: no such file or directory
core@core3 ~ $ etcdctl ls /
Error:  dial tcp 127.0.0.1:2379: getsockopt: connection refused
```

Is there any way to launch a functioning/configured cluster with corectl alone or should I use another tool like Vagrant/bash script to configure the machines?

**Comment by rimusz** [comment]
@olalonde `correctl` uses what ever CoreOS `cloud-config` you provided.
If you have etcd/fleet enable in your `cloud-config` that will work fine.

For the master+ 2nodes cluster examples take a look to https://github.com/TheNewNormal/kube-cluster-osx/tree/master/src/cloud-init files, for the single one VM with etcd/fleet enabled https://github.com/TheNewNormal/coreos-osx/tree/master/src/cloud-init

**Comment by olalonde** [comment]
Thanks! Would be nice if you could eventually extract those files/scripts so they can be used without the status bar app.
