### ISSUE TITLE
CoreOS 1053.2.0 won't start

### ISSUE THREAD

**Issue by jacobat** [AntonioMeireles/coreos-xhyve#73]
Not sure if this is the right place to report this.

Trying to start corectl I see:

```
$ sudo corectl run --cloud_config https://raw.githubusercontent.com/TheNewNormal/corectl/golang/cloud-init/docker-only-with-persistent-storage.txt
[corectl] downloading and verifying alpha/1053.2.0
Error: Signature check for DIGESTS failed.
```

**Comment by AntonioMeireles** [comment]
Hi again, 

Thanks for reporting! 

afaict [0.5.7](https://github.com/TheNewNormal/corectl/releases/tag/v0.5.7) fixed this specific issue (0.5.8 is already out btw) . are you running a recent version ?

**Comment by jacobat** [comment]
I was running 0.5.6 - upgrading does indeed fix this - sorry for the noise!

**Comment by AntonioMeireles** [comment]
No problem :-), you're welcome!  hope you're enjoying `coreclt` !
