### ISSUE TITLE
unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist

### ISSUE THREAD

**Issue by rimusz** [AntonioMeireles/coreos-xhyve#83]
it is the second user reporting this issue, and it is only related to the new v0.7.x.
@AntonioMeireles could be hyperkit problem ?

**Comment by rimusz** [comment]
Shall we check for the `com.apple.vmnet.plist` file and if not found copy from the template there ?

**Comment by AntonioMeireles** [comment]
morning. totally unrelated with hyperkit. that was #80 which got an incomplet fix. new push on the way.

**Comment by AntonioMeireles** [comment]
reopened #80
