### ISSUE TITLE
Why is corectl writing data to the disk all the time

### ISSUE THREAD

**Issue by RaeesBhatti** [AntonioMeireles/coreos-xhyve#89]
I just noticed that the `corectld` has been writing data to the disk at ~300kbps even when there is no active VMs. In a few hours it wrote some GigaBytes actually. Is this supposed to happen? What is it writing?
Server Version: `v0.7.13`
Active VMs: `0`

**Comment by RaeesBhatti** [comment]
I also noticed that `corectld` has a higher energy impact (~30) compared to Docker for Mac (~10) for nearly identical application deployed on Kubernetes.

**Comment by AntonioMeireles** [comment]
Hi @raeesiqbal 

first let us thak you for your fededback. The I/O pattern you're seeing is _just_ our embedded etcd doing its stuff - snapshotting, etc. I'm open to better etcd setup defaults but at sight what we have looks reasonable. 

re: energy impact if we want to compare apples to apples for any given workload you need to compare the sum of all the involved components. So, for Docker for Mac you 'd have to sum com.docker.osx.hyperkit.linux, com.docker.driver.amd64-linux, com.docker.frontend, com.docker.vmnetd, and the applet itsef - Docker, and on our side you'd have to sum corectld, and corectld.runner. _IF_ after doing that we'd still have big discrepancies then it's a bug in our side, but afaict we don't.

**Comment by RaeesBhatti** [comment]
I'm new to etcd but if I understand correctly the snapshot should be taken after every 10,000 changes, by default. Now the question is, why is etcd making 10,000 changes every second even when there is no active VM?

**Comment by AntonioMeireles** [comment]
it's not necessarly 10k changes/sec - the i/o values you get are an average :-) otoh plz do note that if you point your macOS host to corectld's dns inevitabbly etcd will get a lot of traffic...
